application: zylocation
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  script: location_server.application
  login: required

- url: /report.*
  script: location_server.application
  login: optional

- url: /get.*
  script: location_server.application
  login: optional
